<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateClimasTable extends Migration
{   
    public function up()
    {
        Schema::create('climas', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('fk_id_plantillas')->default("1");
            $table->string('fk_cve_periodo',3)->default("221");
            $table->timestamp('fecha')->nullable();
            $table->string('area',180)->default("DESARROLLO ORGANIZACIONAL"); 
            $table->tinyInteger('r1')->default("0");
            $table->tinyInteger('r2')->default("0");
            $table->tinyInteger('r3')->default("0");
            $table->tinyInteger('r4')->default("0");
            $table->tinyInteger('r5')->default("0");
            $table->tinyInteger('r6')->default("0");
            $table->tinyInteger('r7')->default("0");
            $table->tinyInteger('r8')->default("0");
            $table->tinyInteger('r9')->default("0");
            $table->tinyInteger('r10')->default("0");
            $table->tinyInteger('r11')->default("0");
            $table->tinyInteger('r12')->default("0");
            $table->tinyInteger('r13')->default("0");
            $table->tinyInteger('r14')->default("0");
            $table->tinyInteger('r15')->default("0");
            $table->tinyInteger('r16')->default("0");
            $table->tinyInteger('r17')->default("0");
            $table->tinyInteger('r18')->default("0");
            $table->tinyInteger('r19')->default("0");
            $table->tinyInteger('r20')->default("0");
            $table->tinyInteger('r21')->default("0");
            $table->tinyInteger('r22')->default("0");
            $table->tinyInteger('r23')->default("0");
            $table->tinyInteger('r24')->default("0");
            $table->tinyInteger('r25')->default("0");
            $table->tinyInteger('r26')->default("0");
            $table->tinyInteger('r27')->default("0");
            $table->tinyInteger('r28')->default("0");
            $table->tinyInteger('r29')->default("0");
            $table->tinyInteger('r30')->default("0");
            $table->tinyInteger('r31')->default("0");
            $table->tinyInteger('r32')->default("0");
            $table->tinyInteger('r33')->default("0");
            $table->tinyInteger('r34')->default("0");
            $table->tinyInteger('r35')->default("0");
            $table->tinyInteger('r36')->default("0");
            $table->tinyInteger('r37')->default("0");
            $table->tinyInteger('r38')->default("0");
            $table->tinyInteger('r39')->default("0");
            $table->tinyInteger('r40')->default("0");
            $table->tinyInteger('r41')->default("0");
            $table->tinyInteger('r42')->default("0");
            $table->tinyInteger('r43')->default("0");
            $table->tinyInteger('r44')->default("0");
            $table->tinyInteger('r45')->default("0");
            $table->tinyInteger('r46')->default("0");
            $table->tinyInteger('r47')->default("0");
            $table->tinyInteger('r48')->default("0");
            $table->tinyInteger('r49')->default("0");
            $table->tinyInteger('r50')->default("0");
            $table->tinyInteger('r51')->default("0");
            $table->tinyInteger('r52')->default("0");
            $table->tinyInteger('r53')->default("0");
            $table->tinyInteger('r54')->default("0");
            $table->tinyInteger('r55')->default("0");
            $table->tinyInteger('r56')->default("0");
            $table->tinyInteger('r57')->default("0");
            $table->tinyInteger('r58')->default("0");
            $table->tinyInteger('r59')->default("0");
            $table->tinyInteger('r60')->default("0");
            $table->tinyInteger('r61')->default("0");
            $table->tinyInteger('r62')->default("0");
            $table->tinyInteger('r63')->default("0");
            $table->tinyInteger('r64')->default("0");
            $table->tinyInteger('r65')->default("0");
            $table->tinyInteger('r66')->default("0");
            $table->tinyInteger('r67')->default("0");
            $table->tinyInteger('r68')->default("0");
            $table->tinyInteger('r69')->default("0");
            $table->tinyInteger('r70')->default("0");
            $table->tinyInteger('r71')->default("0");
            $table->tinyInteger('r72')->default("0");
            $table->tinyInteger('r73')->default("0");
            $table->tinyInteger('r74')->default("0");
            $table->tinyInteger('r75')->default("0");
            $table->tinyInteger('r76')->default("0");
            $table->tinyInteger('r77')->default("0");
            $table->tinyInteger('r78')->default("0");
            $table->tinyInteger('r79')->default("0");
            $table->tinyInteger('r80')->default("0");
            $table->tinyInteger('r81')->default("0");
            $table->tinyInteger('r82')->default("0");
            $table->tinyInteger('r83')->default("0");
            $table->tinyInteger('r84')->default("0");
            $table->tinyInteger('r85')->default("0");
            $table->tinyInteger('r86')->default("0");
            $table->tinyInteger('r87')->default("0");
            $table->tinyInteger('r88')->default("0");
            $table->tinyInteger('r89')->default("0");
            $table->tinyInteger('r90')->default("0");
            $table->tinyInteger('r91')->default("0");
            $table->tinyInteger('r92')->default("0");
            $table->tinyInteger('r93')->default("0");
            $table->tinyInteger('r94')->default("0");
            $table->tinyInteger('r95')->default("0");
            $table->tinyInteger('r96')->default("0");
            $table->tinyInteger('r97')->default("0");
            $table->tinyInteger('r98')->default("0");
            $table->tinyInteger('r99')->default("0");
            $table->tinyInteger('r100')->default("0");
            $table->tinyInteger('r101')->default("0");
            $table->tinyInteger('r102')->default("0");
            $table->tinyInteger('r103')->default("0");
            $table->tinyInteger('r104')->default("0");
            $table->boolean('activo')->default(true);
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('fk_cve_periodo')->references('cve_periodo')->
            on('periodos')->onDelete('cascade');
            $table->foreign('fk_id_plantillas')->references('id')->
            on('plantillas')->onDelete('cascade');
        });        
    }
    public function down()
    {
        Schema::dropIfExists('climas');
    }
}